[package]
name = "rust-lib-sample"
version = "0.1.0"
authors = ["goya813 <wasabibeef@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
